### ISSUE TITLE
RS232 - Serial Communication

### ISSUE THREAD

**Issue by Deph0** [mclear/Sesame#12]
Being able to talk to a reader with is made up by a dev-board such as a Arduino with a NFC-Shield or the like would open up a lot of possibilities for developers creating their own solution, without having to use pre-existing usb-nfcreaders.

This would likely need some sort of protocol to function, with handshake implementation for discovery of said reader.

**Comment by maz-net-au** [comment]
Do you know of a nfc reader shield or something that i can buy to build this for? I have a pile of Arduino boards already.

**Comment by JohnMcLear** [comment]
Keyduino?

**Comment by maz-net-au** [comment]
I think there is an add-on that just adds nfc functionality to and existing Arduino compatible board. I'll investigate more tomorrow. If i can nfc enable one of my esp8266 I'll be able to make a really funky wireless lock. Otherwise I'll see how much a keyduino costs.

**Comment by JohnMcLear** [comment]
Pn532 board


________________________________

**Comment by maz-net-au** [comment]
Added a simple RS232 example and a description of the protocol that the service expects to be implemented. 
Works with my Uno and PN532 shield.

**Comment by Deph0** [comment]
Fixed in commites 6ab783d818c43f8cd03cbac9a7accdec69137313 , 34942b2535178539392f63c4d966e721144d9a18 , 3ec07b46307512ff5af2d5c4dbd423ff9bda7a54 , 86ecbf395b058bf091c2b0a36c9fabcaf9d11b8c

Just for posterity, would be nice if you could mention the issue in your commits with #-issuenumber

**Comment by maz-net-au** [comment]
No problem. I can do that in the future.
