### ISSUE TITLE
Decide on name

### ISSUE THREAD

**Issue by JohnMcLear** [mclear/Sesame#17]
Maz doesn't like Sesame..

Tempted to just put it as "NFC Ring Unlock" and match it up with our other app options that way it's a single point of entry for a user and we can try to have a similar experience across devices..  That said, we don't need "NFC Ring Unlock" moving forwards as it's now native soo....  yea..  Assigning @StyleMaster who probably has more interest in brand stuff than me..

**Comment by maz-net-au** [comment]
For the record, I'll keep working on it regardless of the name. I just feel so... Lame.. Every time I have to type it on the chat. If everyone likes the name or no one thinks of a better one I'll just have to quit complaining. :P

As far as the built in NFC unlock stuff goes, I'm still using your app as it's far more reliable than Google's solution and it doesn't appear that they are going to do anything to address that bug.

**Comment by DNThomas** [comment]
Name changed to "NFCRing - Fence"
