### ISSUE TITLE
Window 10 service stop

### ISSUE THREAD

**Issue by JohnMcLear** [mclear/Sesame#2]
In some instances with Windows 10 the service will stop after a minute on the lock screen. You then need to log in manually and restart the service.

**Comment by maz-net-au** [comment]
Does the service stop? or does the credential provider itself die? it appears that i need to use a newer version of the ICredentialProvider interface for windows 10 support.
This means I need to probably duplicate the functionality of my current providers into a separate new set for later windows versions, and use the original ones for older windows versions.
For me it takes 30 seconds before the provider crashes. if you're watching the login screen you can see the wait icon appear momentarily.

**Comment by maz-net-au** [comment]
relevant link of others having the same problem
https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/d68e46ad-2966-4768-9aea-170fdb102ca5/credential-provider-interface-on-windows-10-tcp-10041?forum=windowssecurity

**Comment by maz-net-au** [comment]
Please try the new version and let me know if the problem is fixed. i explicitly corrected for this.

**Comment by Deph0** [comment]
Closed due to negligence in response.  Likely fixed.
