### ISSUE TITLE
Allow user management of registered rings / tokens

### ISSUE THREAD

**Issue by DNThomas** [mclear/Sesame#21]
Currently users only have to ability to remove registered rings and these are shown with a calculated "hash" value. Users should be able to assign/edit friendly names or icons to their registered devices.

**Comment by DNThomas** [comment]
Issue resolved in the UI by Andrey

**Comment by Deph0** [comment]
Added in commits between 3084abb5f139a6fcb742263c9efbab5ce0185fdc and  6f5e1126b496cbd8c44aded426499f74f5d55972 .
