### ISSUE TITLE
Win10 Lockscreen goes to account selection when locked

### ISSUE THREAD

**Issue by DNThomas** [mclear/Sesame#25]
On a standard Win10 machine without the app .. what you lock the PC .. it goes to a standard lock screen. Upon touching the mouse or keyboard, the machine will switch to account selection / password entry.

When the app is installed and the PC then locked, it switches focus immediately to the account selection. This may be due to the background polling ?

**Comment by maz-net-au** [comment]
So if I just go to the standard lock screen, you'll have to press a key and make sure the nfc ring account is selected before swiping the ring. 
Is that acceptable?

**Comment by sentimental37** [comment]
Task #25 Changes, now the user has the option to keep NFC Fence as default login or not. By default it will not be default, means you need to select the NFC Credential Tile to login, and no issues will be there, and if user sets it as default, it will behave like earlier, it will open the login screen as soon as you come to lock screen

**Comment by maz-net-au** [comment]
I fixed this properly yesterday, pending testing.

**Comment by maz-net-au** [comment]
Works on all of my PC's for win 8.1 and win 10.
