### ISSUE TITLE
Create a "Getting started Wizard" that is super easy to use.

### ISSUE THREAD

**Issue by JohnMcLear** [mclear/Sesame#9]

**Comment by janrod** [comment]
Adding UI flow + assets
[sesame-ui.pdf](https://github.com/mclear/Sesame/files/1373748/sesame-ui.pdf)
[assets.zip](https://github.com/mclear/Sesame/files/1373749/assets.zip)

**Comment by kamilovikram** [comment]
How many developers are you looking for?

**Comment by maz-net-au** [comment]
I think one would easily be able to get this done very quickly. The main part of the system is already written and this is just to create a UI wizard for that. A C# dev who understands async network programming could get a version working in less than a day.

**Comment by steelmaker** [comment]
Hello. I can create this wizard. But I don't know logic of application. What api used between wizard steps switching?

**Comment by JohnMcLear** [comment]
@steelmaker you will need to speak to @maz-net-au

**Comment by steelmaker** [comment]
Can I speak In this issue with @maz-net-au or in another way?
Have I right for branch creation?
I ask because I have one error:
remote: Permission to mclear/Sesame.git denied to steelmaker.
fatal: unable to access 'https://github.com/mclear/Sesame.git/': The requested URL returned error: 403

**Comment by JohnMcLear** [comment]
@steelmaker I suggest you do a basic getting started with Git guide before talking to @maz-net-au

**Comment by steelmaker** [comment]
@maz-net-au You can see the my solution https://github.com/steelmaker/Sesame/tree/issue_9

**Comment by JohnMcLear** [comment]
@steelmaker it appears upwork is a problem for you, feel free to contact me directly.  My email address is in my profile

**Comment by maz-net-au** [comment]
@steelmaker
What are the dependencies to be able to compile and run your code? It looks like you've used C# 6 and targeted .net 4.6.1. Did you use VS2015 or VS2017?

**Comment by steelmaker** [comment]
@maz-net-au yes, VS2017, .net 4.6.1. If this is problem I can modify to VS2015 and with any .net framework. What is preferable for us?

**Comment by steelmaker** [comment]
@maz-net-au I modified for .net 4.5 VS2015

**Comment by Deph0** [comment]
I'm closing this because OP issue was addressed, there may however be bugs left unfixed. Please address those in a separate issue if you like to discuss them on a later date.
